### ISSUE TITLE
Cannot find TicketTelegramGroup::Token

### ISSUE THREAD

**Issue by nhenpanha** [mo-azfar/OTRS-Ticket-Notification-To-Telegram-Group#1]
Good afternoon Mo Azfar!

May I know where can i see TicketTelegramGroup::Token?

**Comment by nhenpanha** [comment]
![image](https://user-images.githubusercontent.com/11862935/104697775-d781d400-5742-11eb-91ae-4ae2984215b8.png)

**Comment by mo-azfar** [comment]
> Good afternoon Mo Azfar!
> 
> May I know where can i see TicketTelegramGroup::Token?

Hi there,

After deployed the xml file to right location with correct permission, you must rebuild and sync the config (as otrs user).

```
otrs@shell > bin/otrs.Console.pl Maint::Config::Rebuild --cleanup
otrs@shell > bin/otrs.Console.pl Maint::Config::Sync
```

After that, you can see it from System Configuration. 

Good luck.
